spring:
  application:
    name: rabbitmq_sender_2026

  main:
    banner-mode: off

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 1q2w3e4R
    virtual-host: /
    publisher-confirm-type: correlated # correlated 表示开启发布确认，并且可以通过 CorrelationData 对应是哪一条消息。
    publisher-returns: true # 这个不是确认“有没有到 exchange”，而是判断“消息到了 exchange 之后，是否能路由到 queue”。

app:
  rabbitmq:
    exchange: order.exchange
    routing-key: order.created

server:
  port: 38081